version: '2'
services:
  service2:
    build:
      context: ./kafka
      args:
        - MASHLING_NAME
        - ROOT_DIR
      dockerfile: Dockerfile-kafka-mashling
    volumes:
      - ${ROOT_DIR}/kafka/kafka-mashling-envoy.json:/etc/service-envoy.json
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
      - KAFKA_BROKER_URL=${KAFKA_BROKER_URL}
    expose:
      - "80"

networks:
  envoymesh: {}
