apiVersion: v1
kind: Service
metadata:
  name: gwservice
  labels:
    app: gateway-router
spec:
  selector:
    app: gateway-router
  ports:
  - port: 9096
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer